#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:30:00
#PBS -N realtimeScrape
#PBS -j oe

cd /users/a/r/areagan/scratch/realtime-parsing

for MINUTE in 00 15 30 45
do
  export MINUTE
  echo "processing ${DATE}-${HOUR}-${MINUTE}"
  /usr/bin/time -v gzip -cd /users/c/d/cdanfort/scratch/twitter/tweet-troll/zipped-raw/${DATE}/${DATE}-${HOUR}-${MINUTE}.gz | python realtime.py "${DATE}" "${DATE}-${HOUR}-${MINUTE}"
done

echo "delete me"

