#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:00:00
#PBS -N realtimeScrape
#PBS -j oe

cd /users/a/r/areagan/scratch/realtime-parsing

for HOUR in 0{0..9} {10..23}
do
  export HOUR
  for MINUTE in 00 15 30 45
  do
    export MINUTE
    echo "processing ${DATE}-${HOUR}-${MINUTE}"
    /usr/bin/time -v gzip -cd /users/c/d/cdanfort/scratch/twitter/tweet-troll/zipped-raw/${DATE}/${DATE}-${HOUR}-${MINUTE}.gz | python realtime.py "${DATE}" "${DATE}-${HOUR}-${MINUTE}"
  done
done

echo "delete me"

